# Generated by Django 4.2.6 on 2023-11-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_type',
            name='labels',
        ),
        migrations.AddField(
            model_name='case',
            name='labels',
            field=models.ManyToManyField(to='API.labels'),
        ),
    ]
