# Generated by Django 4.2.6 on 2023-11-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_category_type_labels_case_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slice',
            old_name='zoom',
            new_name='image_id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='slice',
        ),
        migrations.AddField(
            model_name='category_type',
            name='slice',
            field=models.ManyToManyField(blank=True, default=0, to='API.slice'),
        ),
        migrations.AddField(
            model_name='slice',
            name='labels',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slice',
            name='options',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slice',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
