# Generated by Django 4.2.6 on 2023-10-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_case_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='columns',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='rows',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
