# Generated by Django 4.2.6 on 2023-11-08 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_category_type_slice_slice_case_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
