# Generated by Django 4.2.6 on 2023-11-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_session_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='session',
            name='rows',
        ),
        migrations.CreateModel(
            name='Reference_Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ManyToManyField(blank=True, to='API.image')),
            ],
        ),
    ]
