# Generated by Django 4.2.6 on 2023-11-01 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_remove_session_columns_remove_session_rows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_type',
            name='slice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.slice'),
        ),
    ]
