# Generated by Django 4.2.6 on 2023-11-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_slice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='slice',
            name='category_type',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
