# Generated by Django 4.2.6 on 2023-11-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_slice_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slice',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='slice',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='slice',
            name='project_id',
        ),
        migrations.AddField(
            model_name='slice',
            name='case_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slice',
            name='category_type_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slice',
            name='project_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
