# Generated by Django 4.2.6 on 2023-11-01 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_category_type_slice'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='reference_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.reference_folder'),
        ),
    ]
