# Generated by Django 4.2.6 on 2023-11-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_case_reference_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='labels',
        ),
        migrations.AddField(
            model_name='case',
            name='labels',
            field=models.ManyToManyField(to='API.labels'),
        ),
        migrations.AddField(
            model_name='case',
            name='notes',
            field=models.TextField(default='migrations_happened'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='randomize_cases',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='randomize_categories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='options',
            field=models.ManyToManyField(to='API.options'),
        ),
    ]
