# Generated by Django 4.2.6 on 2023-11-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_project_slicesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_name',
            field=models.CharField(default='testing session  name', max_length=200),
            preserve_default=False,
        ),
    ]
