# Generated by Django 4.2.6 on 2023-11-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_options_remove_session_labels_case_labels_case_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='name',
            new_name='case_name',
        ),
        migrations.RenameField(
            model_name='reference_folder',
            old_name='name',
            new_name='reference_name',
        ),
    ]
