# Generated by Django 4.2.6 on 2023-11-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_session_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
