# Generated by Django 4.2.6 on 2023-11-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_rename_name_case_case_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
