# Generated by Django 4.2.6 on 2023-11-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_case_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='case_name',
            new_name='name',
        ),
    ]
