# Generated by Django 4.2.6 on 2023-11-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_case_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='score',
        ),
        migrations.AddField(
            model_name='category_type',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
