# Generated by Django 4.2.6 on 2023-11-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_remove_case_score_category_type_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
