# Generated by Django 4.2.6 on 2023-11-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_rename_case_name_case_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='name',
            new_name='case_name',
        ),
    ]
