# Generated by Django 4.2.6 on 2023-11-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_rename_name_case_case_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference_folder',
            old_name='reference_name',
            new_name='name',
        ),
    ]
