# Generated by Django 4.2.6 on 2023-11-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_remove_project_slicesession_delete_slicesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_type',
            name='score',
        ),
        migrations.RemoveField(
            model_name='slice',
            name='score',
        ),
        migrations.AddField(
            model_name='labels',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labels',
            name='type',
            field=models.CharField(default='string', max_length=200),
            preserve_default=False,
        ),
    ]
