# Generated by Django 4.2.6 on 2023-11-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_rename_reference_name_reference_folder_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference_folder',
            old_name='name',
            new_name='reference_name',
        ),
    ]
