# Generated by Django 4.2.6 on 2023-11-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_rename_name_reference_folder_reference_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='case_name',
            new_name='name',
        ),
    ]
