# Generated by Django 4.2.6 on 2023-11-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_labels_range_alter_labels_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labels',
            name='range',
        ),
        migrations.RemoveField(
            model_name='labels',
            name='type',
        ),
    ]
