# Generated by Django 4.2.6 on 2023-11-02 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_rename_name_case_case_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labels',
            old_name='label_name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='options',
            old_name='option_name',
            new_name='value',
        ),
    ]
