# Generated by Django 4.2.6 on 2023-11-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_alter_labels_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='score',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
