# Generated by Django 4.2.6 on 2023-11-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_rename_label_name_labels_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slice',
            name='labels',
            field=models.ManyToManyField(to='API.labels'),
        ),
        migrations.AddField(
            model_name='slice',
            name='options',
            field=models.ManyToManyField(to='API.options'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/API/dicom_images/'),
        ),
    ]
