# Generated by Django 4.2.6 on 2023-11-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_slice_labels_slice_options_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='API/dicom_images/'),
        ),
    ]
