# Generated by Django 4.2.6 on 2023-11-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_session_slice_slice_score_slice_session_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='slice',
            field=models.ManyToManyField(blank=True, null=True, to='API.slice'),
        ),
    ]
