# Generated by Django 4.2.6 on 2023-11-03 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_case_cols_number_case_rows_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_type',
            name='slice',
        ),
        migrations.AddField(
            model_name='image',
            name='slice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.slice'),
        ),
    ]
