# Generated by Django 4.2.6 on 2023-11-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_remove_category_type_slice_image_slice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zip_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(upload_to='API/ZipFile')),
            ],
        ),
    ]
