# Generated by Django 4.2.6 on 2023-11-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0022_zip_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zip_file',
            old_name='zip_file',
            new_name='uploaded_file',
        ),
    ]
