# Generated by Django 4.2.6 on 2023-11-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0023_rename_zip_file_zip_file_uploaded_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zip_File',
            new_name='ZipFile',
        ),
    ]
