# Generated by Django 4.2.6 on 2023-11-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0023_remove_case_notes_project_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='notes',
        ),
        migrations.AddField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
