# Generated by Django 4.2.6 on 2023-11-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0024_rename_zip_file_zipfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='slice',
            name='opacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
