# Generated by Django 4.2.6 on 2023-11-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_slice_opacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slice',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='slice',
            name='opacity',
        ),
        migrations.RemoveField(
            model_name='slice',
            name='options',
        ),
        migrations.AddField(
            model_name='labels',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='options',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='options',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
