# Generated by Django 4.2.6 on 2023-12-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0026_remove_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
